### PR TITLE
allineamento dev > test

### PR DESCRIPTION
**Pull request by nnzJd**
Alligned new configurations 'from' branch dev to branch 'test'
@ioggstream

### CODE REVIEW

**Review by ioggstream — COMMENTED** [review]
@nnzJd can you re-update? we released a new front-end just now.

**Comment by nnzJd** [comment]
> @nnzJd can you re-update? we released a new front-end just now.

Done

**Comment by nnzJd** [comment]
> > @nnzJd can you re-update? we released a new front-end just now.
> 
> Done

@ioggstream

**Comment by ioggstream** [comment]
@nnzJd @gnespolino pls always mention @CreaIstat for test/ PRs

**Review by CreaIstat — APPROVED** [review]

**Pull request merged**
